# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DVCP <- function(mcmc_samples, burnin, thin, adapt, likelihood_indicator, h_model, approx_angles, y, x, distance_to_ps, unique_angles, angle_key, metrop_var_lambda, metrop_var_eta, metrop_var_phi_eta, adapt_lambda, adapt_eta, adapt_phi_eta, alpha_sigma2_epsilon_prior = NULL, beta_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, sigma2_theta_prior = NULL, a_lambda_prior = NULL, b_lambda_prior = NULL, alpha_sigma2_eta_prior = NULL, beta_sigma2_eta_prior = NULL, alpha_phi_eta_prior = NULL, beta_phi_eta_prior = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, theta_init = NULL, lambda_init = NULL, sigma2_eta_init = NULL, phi_eta_init = NULL) {
    .Call(`_DVCP_DVCP`, mcmc_samples, burnin, thin, adapt, likelihood_indicator, h_model, approx_angles, y, x, distance_to_ps, unique_angles, angle_key, metrop_var_lambda, metrop_var_eta, metrop_var_phi_eta, adapt_lambda, adapt_eta, adapt_phi_eta, alpha_sigma2_epsilon_prior, beta_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_theta_prior, a_lambda_prior, b_lambda_prior, alpha_sigma2_eta_prior, beta_sigma2_eta_prior, alpha_phi_eta_prior, beta_phi_eta_prior, sigma2_epsilon_init, beta_init, theta_init, lambda_init, sigma2_eta_init, phi_eta_init)
}

beta_update <- function(x, indicator, omega, kappa, theta, sigma2_beta) {
    .Call(`_DVCP_beta_update`, x, indicator, omega, kappa, theta, sigma2_beta)
}

eta_update <- function(k_approx, cross_a_approx, eta_approx_corr_inv, h_model, distance_to_ps, angle_key, x, indicator, omega, kappa, beta, theta, lambda, eta, eta_approx, sigma2_eta, phi_eta, metrop_var_eta, acctot_eta) {
    .Call(`_DVCP_eta_update`, k_approx, cross_a_approx, eta_approx_corr_inv, h_model, distance_to_ps, angle_key, x, indicator, omega, kappa, beta, theta, lambda, eta, eta_approx, sigma2_eta, phi_eta, metrop_var_eta, acctot_eta)
}

indicator_fun <- function(h_model, distance_to_ps, angle_key, lambda, eta) {
    .Call(`_DVCP_indicator_fun`, h_model, distance_to_ps, angle_key, lambda, eta)
}

lambda_update <- function(h_model, distance_to_ps, angle_key, x, indicator, omega, kappa, beta, theta, lambda, eta, a_lambda, b_lambda, metrop_var_lambda, acctot_lambda) {
    .Call(`_DVCP_lambda_update`, h_model, distance_to_ps, angle_key, x, indicator, omega, kappa, beta, theta, lambda, eta, a_lambda, b_lambda, metrop_var_lambda, acctot_lambda)
}

neg_two_loglike_update <- function(likelihood_indicator, y, x, indicator, sigma2_epsilon, beta, theta) {
    .Call(`_DVCP_neg_two_loglike_update`, likelihood_indicator, y, x, indicator, sigma2_epsilon, beta, theta)
}

omega_update <- function(y, x, indicator, beta, theta) {
    .Call(`_DVCP_omega_update`, y, x, indicator, beta, theta)
}

phi_eta_update <- function(d_a_approx, cross_a_approx, eta_approx_corr_inv, h_model, distance_to_ps, angle_key, x, indicator, omega, kappa, beta, theta, lambda, eta, eta_approx, sigma2_eta, phi_eta, alpha_phi_eta, beta_phi_eta, metrop_var_phi_eta, acctot_phi_eta) {
    .Call(`_DVCP_phi_eta_update`, d_a_approx, cross_a_approx, eta_approx_corr_inv, h_model, distance_to_ps, angle_key, x, indicator, omega, kappa, beta, theta, lambda, eta, eta_approx, sigma2_eta, phi_eta, alpha_phi_eta, beta_phi_eta, metrop_var_phi_eta, acctot_phi_eta)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_DVCP_rcpp_pgdraw`, b, c)
}

sigma2_epsilon_update <- function(y, x, indicator, beta, theta, alpha_sigma2_epsilon, beta_sigma2_epsilon) {
    .Call(`_DVCP_sigma2_epsilon_update`, y, x, indicator, beta, theta, alpha_sigma2_epsilon, beta_sigma2_epsilon)
}

sigma2_eta_update <- function(eta_approx_corr_inv, eta_approx, alpha_sigma2_eta, beta_sigma2_eta) {
    .Call(`_DVCP_sigma2_eta_update`, eta_approx_corr_inv, eta_approx, alpha_sigma2_eta, beta_sigma2_eta)
}

theta_update <- function(x, indicator, omega, kappa, beta, sigma2_theta) {
    .Call(`_DVCP_theta_update`, x, indicator, omega, kappa, beta, sigma2_theta)
}

